swagger: '2.0'
info:
  version: "0.0.1"
  title: "<math><mtext></form><form><mglyph><style></math><img src onerror=alert(1)>"
  description: "<math><mtext></form><form><mglyph><style></math><img src onerror=alert(1)>"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
